name: "🚥 Create Jira Release"
description: "Create a Jira 'Fix Version' for one or more projects."

inputs:
  JIRA_URL:
    description: "Jira Instance URL."
    required: true
  JIRA_API_URL:
    description: "Jira API URL, if on another domain."
    required: false
  JIRA_API_KEY:
    description: "Jira API TOKEN."
    required: true
  JIRA_API_USER:
    description: "Jira API User."
    required: true
  JIRA_PROJECT_KEYS:
    description: "An comma-separated list of Jira Project 'Keys'. Use quotes for fancy characters (Beta Feature)."
    required: true
    default: "RM"
  JIRA_RELEASE_IDENTIFIER:
    description: "Jira version identifier. E.g. 24.05.04.0 or 24.Q2.3.0."
    required: true
    default: "YY.QQ.NN.I"
  JIRA_RELEASE_DESCRIPTION:
    description: "Jira version description. Shared across releases generated."
    required: false
  JIRA_RELEASE_NOW:
    description: "Whether the version should be marked released."
    required: false
    default: "false"

outputs:
  JIRA_RELEASE_NAME:
    description: "The resulting Jira Version name(s)."
  JIRA_VERSION_URL:
    description: "The resulting Jira Version URL(s)."

runs:
  using: "node20"
  main: dist/index.js
