name: Dependabot Issues
run-name: "🗑️ Closing PR: `${{github.event.pull_request.title}}` and creating an issue instead."
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [opened, reopened]

jobs:
  create_issue:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@v4
        if: github.event.pull_request.user.login  == 'dependabot[bot]'

      - name: Open issue and close Dependabot PR
        if: github.event.pull_request.user.login  == 'dependabot[bot]'
        env:
          pr_title: ${{github.event.pull_request.title}}
          pr_number: ${{github.event.pull_request.number}}
          pr_url: ${{github.event.pull_request.url}}
        run: |
          title="Dependabot PR $pr_title opened"
          body="Dependabot has opened PR #$pr_number
          Link: $pr_url"
          gh issue create --title "$title" --body "$body"

  close_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Close the Pull Request
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo, number } = context.issue;
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
            await octokit.rest.pulls.update({
              owner,
              repo,
              pull_number: number,
              state: 'closed'
            });

            // Comment on the PR with a link to the created issue.
            await octokit.rest.issues.createComment({
              owner,
              repo,
              issue_number: number,
              body: "This pull request has been automatically closed and documented in [#$GITHUB_ISSUE_NUM]($GITHUB_ISSUE_LINK): $GITHUB_ISSUE_TITLE."
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
