name: "Hello World"
run-name: "Hello World"

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
  push:
    branches: [develop, main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # Note many defaults are explicity included below for implicit documentation
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          ref: ${{ github.event.pull_request.head.sha || github.head_ref || github.ref_name }}
          token: ${{ github.token }}
          show-progress: true
          fetch-depth: 0

      - name: "Hello World"
        id: hello-world
        uses: ./actions/hello-world
        with:
          who-to-greet: "Sammy the Snail"
          milliseconds: 1000

      - name: "Hello World Summary"
        run: |
          echo "Such time — ${{ steps.hello-world.outputs.time }}ms — Wow!" >> $GITHUB_STEP_SUMMARY
