name: "🚥 Tests: Create Jira Release"
run-name: "🚥 Test Create Jira Release: `${{ inputs.JIRA_PROJECT_KEY }}-R${{ inputs.JIRA_RELEASE_IDENTIFIER }}`"

on:
  workflow_dispatch:
    inputs:
      JIRA_PROJECT_KEY:
        type: choice
        description: "The Jira project key this version will be created in."
        required: true
        options:
          - DG
          - RM

      JIRA_RELEASE_IDENTIFIER:
        description: "The version identifier, which will be concatenated with 'KEY-R-'."
        required: true
        default: "YY.QQ.N.N.0"

      JIRA_RELEASE_DESCRIPTION:
        description: "A description of the Jira version."
        required: false

      JIRA_RELEASE_NOW:
        description: "Release the Version immediately?"
        required: true
        default: false
        type: boolean

concurrency:
  group: "release-request"
  cancel-in-progress: true

jobs:
  create-jira-release:
    name: "🚥 Creating Jira Fix Version `${{ inputs.JIRA_PROJECT_KEY }}-R${{ inputs.JIRA_RELEASE_IDENTIFIER }}`"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          ref: ${{ github.event.pull_request.head.sha || github.head_ref || github.ref_name }}
          token: ${{ github.token }}
          show-progress: true
          fetch-depth: 0

      - name: 🛢 Install Dependencies
        uses: ./.github/actions/install-cache-deps

      - name: "Create Jira Release"
        id: create-jira-release
        uses: ./actions/create-jira-release
        with:
          JIRA_URL: ${{ vars.JIRA_URL }}
          JIRA_API_URL: ${{ vars.JIRA_API_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_API_USER: ${{ secrets.JIRA_API_USER }}
          JIRA_PROJECT_KEY: ${{ inputs.JIRA_PROJECT_KEY }}
          JIRA_RELEASE_IDENTIFIER: ${{ inputs.JIRA_RELEASE_IDENTIFIER }}
          JIRA_RELEASE_DESCRIPTION: ${{ inputs.JIRA_RELEASE_DESCRIPTION }}
          JIRA_RELEASE_NOW: ${{ inputs.JIRA_RELEASE_NOW }}
