name: "🚥 Test Actions"
run-name: "🥽 Test ${{ github.event_name == 'pull_request' && format('PR #{0}: `{1}`', github.event.pull_request.number, github.event.pull_request.title) || format('latest `{0}`', github.ref_name) }}"

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
  push:
    branches: [develop, main]

jobs:
  test:
    name: "Checkout, Install, Test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          ref: ${{ github.event.pull_request.head.sha || github.head_ref || github.ref_name }}
          token: ${{ github.token }}
          show-progress: true
          fetch-depth: 0

      - name: 🛢 Install Dependencies
        uses: ./.github/actions/install-cache-deps

      - name: "Hello World"
        id: hello-world
        uses: ./actions/hello-world
        with:
          who-to-greet: "Sammy the Snail"
          milliseconds: 1000

      - name: "Create Jira Release"
        id: create-jira-release
        uses: ./actions/create-jira-release
        with:
          JIRA_URL: "some kind of test"
          JIRA_API_URL: "some kind of test"
          JIRA_API_TOKEN: "some kind of test"
          JIRA_PROJECT_KEYS: "some kind of test"
          JIRA_RELEASE_IDENTIFIER: "some kind of test"
          JIRA_RELEASE_DESCRIPTION: "some kind of test"
          JIRA_RELEASE_NOW: "some kind of test"

      - name: "Summary"
        run: |
          echo "Such time — ${{ steps.hello-world.outputs.time }}ms — Wow!" >> $GITHUB_STEP_SUMMARY
